spring.application.name=api-gateway
eureka.client.service-url.defaultZone=http://eureka:password@localhost:8761/eureka
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

##Product service Route
spring.cloud.gateway.server.webmvc.routes[0].id=product-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://product-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=path=api/product

##Order service Route
spring.cloud.gateway.server.webmvc.routes[1].id=order-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://order-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=path=api/order

##Discovery server Route
spring.cloud.gateway.server.webmvc.routes[2].id=discovery-server
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8761
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=path=eureka/web
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=SetPath=/

##Discovery server static resources Route
spring.cloud.gateway.server.webmvc.routes[3].id=discovery-server-static
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8761
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=path=eureka/**

##keycloak realms issuer url
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/spring-boot-microservice-realm

##Micrometer and zipkin properties for tracing
management.tracing.sampling.probability= 1.0
##Actuator endpoints
##Prometheus is used to collect metrics data for monitoring purpose
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.tracing.export.zipkin.endpoint= http://localhost:9411/api/v2/spans

##Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.urls[0].name=Product Service
springdoc.swagger-ui.urls[0].url=/aggregate/product-service/v3/api-docs
springdoc.swagger-ui.urls[1].name=Order Service
springdoc.swagger-ui.urls[1].url=/aggregate/order-service/v3/api-docs
springdoc.swagger-ui.urls[2].name=Inventory Service
springdoc.swagger-ui.urls[2].url=/aggregate/inventory-service/v3/api-docs