spring.application.name=inventory-service
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.show-sql=true
server.port=0

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://eureka:password@localhost:8761/eureka

##Micrometer and zipkin properties for tracing
management.tracing.sampling.probability= 1.0
##Actuator endpoints
##Prometheus is used to collect metrics data for monitoring purpose
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.tracing.export.zipkin.endpoint= http://localhost:9411/api/v2/spans
